/**
 * palette-drag-from-tree.spec.ts — ADR 0015 step 1 (#376).
 *
 * Step 1 of the canonical-creation-affordance migration: every visible
 * project-tree group header becomes `draggable`. The drop-side
 * `acceptedElementKinds` guard in CanvasPane.handleDrop continues to gate
 * which (viewpoint, kind) combinations actually create an element — so
 * dragging a kind a viewpoint doesn't accept (e.g. `ActionDefinition` onto
 * a BDD canvas) still no-ops, but the affordance asymmetry rubric dim 15
 * flagged is gone: every kind reads as drag-creatable from the same place.
 *
 * Scope of this spec:
 *  - PartDefinition group header → BDD canvas creates a Block node at the
 *    drop position (the existing #50 / #31 BDD path, now reachable from
 *    the tree drag instead of only the toolbar `+ Block` button).
 *  - ActionDefinition group header → BDD canvas no-ops (guard catches it;
 *    no element + no node created).
 *  - Package group header → Package-viewpoint canvas creates a Package
 *    node at the drop position. Tested against the Package canvas (not
 *    BDD) because BDD's `acceptedElementKinds` is `['PartDefinition']`
 *    and ADR 0015 step 1 explicitly leaves `acceptedElementKinds` alone
 *    (step 2 owns vocabulary + accepted-kind cleanup).
 *
 * Steps 2–4 of ADR 0015 (empty-state cards as shortcuts, toolbar `+ X`
 * retire, inspector `+ New X` rewire) live in separate PRs and do not
 * touch this spec.
 */

import { expect, test, type Page } from '@playwright/test';

async function dragGroupToCanvas(
  page: Page,
  kind: string,
  targetPosition: { x: number; y: number } = { x: 360, y: 220 },
): Promise<void> {
  const group = page.getByTestId(`project-tree-group-${kind}`);
  const canvas = page.getByTestId('canvas-drop-target');
  await group.dragTo(canvas, { targetPosition });
}

test.describe('Palette drag from project tree → canvas (ADR 0015 step 1, #376)', () => {
  test('every visible group header is `draggable` regardless of active viewpoint', async ({
    page,
  }) => {
    // Pre-ADR-0015 only the active viewpoint's palette kinds were draggable.
    // Step 1 lifts that gate: every visible group header carries
    // `draggable="true"`. The viewpoint-specificity moves to the drop-side
    // `acceptedElementKinds` guard.
    await page.goto('/');
    await expect(page.getByTestId('project-tree')).toBeVisible();

    const kinds = [
      'Package',
      'PartDefinition',
      'InterfaceDefinition',
      'PortDefinition',
      'ActionDefinition',
      'StateDefinition',
      'ConstraintDefinition',
      'Requirement',
      'Actor',
      'UseCase',
      'PartUsage',
      'ActionUsage',
      'StateUsage',
      'ConstraintUsage',
      'ValueProperty',
    ];
    for (const kind of kinds) {
      await expect(
        page.getByTestId(`project-tree-group-${kind}`),
        `expected ${kind} group header to be draggable`,
      ).toHaveAttribute('draggable', 'true');
    }
  });

  test('drag PartDefinition group header → BDD canvas creates a Block node', async ({
    page,
  }) => {
    await page.goto('/');
    await expect(page.getByTestId('project-tree')).toBeVisible();
    // Cold-start lands on the BDD canvas.
    await expect(page.getByTestId('canvas-toolbar')).toContainText(
      'Block Definition Diagram',
    );

    const blocksBefore = page.locator('[data-testid^="bdd-block-"][data-element-id]');
    await expect(blocksBefore).toHaveCount(0);

    await dragGroupToCanvas(page, 'PartDefinition');

    // One new PartDefinition node renders on the BDD canvas.
    await expect(blocksBefore).toHaveCount(1);

    // A new PartDefinition element appears in the project tree's
    // Part-Definition group (autogenerated default name).
    await expect(
      page.getByTestId('project-tree-group-PartDefinition'),
    ).toHaveAttribute(
      'aria-label',
      expect.stringMatching(/Part definitions \(1\)/),
    );
  });

  test('drag ActionDefinition group header → BDD canvas is rejected (acceptedElementKinds guard)', async ({
    page,
  }) => {
    await page.goto('/');
    await expect(page.getByTestId('project-tree')).toBeVisible();
    await expect(page.getByTestId('canvas-toolbar')).toContainText(
      'Block Definition Diagram',
    );

    // ActionDefinition group is visible + draggable post-ADR-0015 step 1.
    const adGroup = page.getByTestId('project-tree-group-ActionDefinition');
    await expect(adGroup).toBeVisible();
    await expect(adGroup).toHaveAttribute('draggable', 'true');

    // Snapshot: zero blocks + zero ActionDefinitions in the tree.
    const blocks = page.locator('[data-testid^="bdd-block-"][data-element-id]');
    await expect(blocks).toHaveCount(0);
    await expect(adGroup).toHaveAttribute(
      'aria-label',
      expect.stringMatching(/Action definitions \(0\)/),
    );

    // Drop attempt. BDD's `acceptedElementKinds` is `['PartDefinition']`
    // (ADR 0015 step 1 deliberately leaves this alone), so the drop
    // handler no-ops at the guard before any create-element dispatch.
    await dragGroupToCanvas(page, 'ActionDefinition');

    // No BDD node was created.
    await expect(blocks).toHaveCount(0);
    // The ActionDefinition group count is still 0 — the guard rejected the
    // drop before any create-element command went onto the bus.
    await expect(adGroup).toHaveAttribute(
      'aria-label',
      expect.stringMatching(/Action definitions \(0\)/),
    );
  });

  test('drag Package group header → Package-viewpoint canvas creates a Package node', async ({
    page,
  }) => {
    // Seed a project with a Package diagram tab so we have a Package
    // canvas to drop onto. BDD's `acceptedElementKinds` does not include
    // `Package`, so the drop has to happen on the Package canvas — step 2
    // of ADR 0015 owns the broader "drop any def-kind onto BDD" expansion.
    await page.addInitScript(() => {
      // Strip any prior auto-bootstrapped mbse project keys so the
      // workspace bootstrap loads THIS seeded project (the Playwright
      // worker carries default-bootstrap state across tests).
      for (let i = sessionStorage.length - 1; i >= 0; i -= 1) {
        const k = sessionStorage.key(i);
        if (k && k.startsWith('mbse:v1:project:')) sessionStorage.removeItem(k);
      }
      const key = 'mbse:v1:project:p-palette-drag-pkg';
      const project = {
        id: 'p-palette-drag-pkg',
        name: 'Palette Drag Pkg Seed',
        createdAt: '2026-05-17T10:00:00.000Z',
        modifiedAt: '2026-05-17T10:05:00.000Z',
        elements: [],
        edges: [],
        diagrams: [
          {
            id: 'd-bdd',
            viewpointId: 'bdd',
            name: 'Main BDD',
            positions: {},
          },
          {
            id: 'd-package',
            viewpointId: 'package',
            name: 'System Packages',
            positions: {},
          },
        ],
        history: { undo: [], redo: [] },
      };
      sessionStorage.setItem(key, JSON.stringify(project));
    });

    await page.goto('/');
    const tablist = page.getByRole('tablist', { name: 'Diagram tabs' });
    await tablist.getByRole('tab', { name: 'System Packages' }).click();
    await expect(page.getByTestId('canvas-toolbar')).toContainText(
      'Package Diagram',
    );

    // PackageNode renders three nested testids under the root container
    // (`package-node-<id>` plus `package-node-label-<id>` and
    // `package-node-members-<id>`); narrow with `data-package-node="true"`
    // which is set only on the outer wrapper. The synthesised project-root
    // Package always renders at the canvas origin (toFlowNodes falls back to
    // (0, 0) when a diagram has no position for an element), so the pre-drop
    // baseline is 1, not 0.
    const packageNodes = page.locator('[data-package-node="true"]');
    await expect(packageNodes).toHaveCount(1);

    await dragGroupToCanvas(page, 'Package');

    // One additional Package node now renders on the Package canvas
    // (project-root + the freshly-dropped Package), and the tree group
    // count for Packages has gone up by one to match.
    await expect(packageNodes).toHaveCount(2);
    await expect(
      page.getByTestId('project-tree-group-Package'),
    ).toHaveAttribute(
      'aria-label',
      expect.stringMatching(/Packages \(1\)/),
    );
  });
});
