export const PARAMETRIC_CONSTRAINT_USAGE_WIDTH = 220;
export const PARAMETRIC_CONSTRAINT_USAGE_HEIGHT = 100;
export const PARAMETRIC_VALUE_PROPERTY_WIDTH = 180;
export const PARAMETRIC_VALUE_PROPERTY_HEIGHT = 70;
